INSERT INTO battle_questions (id, text, emoji) VALUES
  ('q_sleep', 'Who can sleep through literally anything?', '😴'),
  ('q_cook', 'Who is most likely to burn down the kitchen?', '🔥'),
  ('q_alien', 'Who is most likely to be abducted by aliens?', '👽'),
  ('q_million', 'Who will be the first millionaire?', '💰'),
  ('q_lost', 'Who always gets lost using GPS?', '🗺️'),
  ('q_gossip', 'Who knows all the gossip?', '🤫'),
  ('q_loud', 'Who is the loudest talker?', '🗣️'),
  ('q_clumsy', 'Who trips over flat surfaces?', '🤕'),
  ('q_diet', 'Who is always "starting a diet tomorrow"?', '🍔'),
  ('q_drama', 'Who causes the most drama?', '🎭'),
  ('q_phone', 'Who is most likely to drop their phone in the toilet?', '📱'),
  ('q_party', 'Who is the life of the party?', '🎉'),
  ('q_ghost', 'Who is most likely to ghost everyone for a week?', '👻'),
  ('q_argue', 'Who argues with the referee/umpire?', '🤬'),
  ('q_sing', 'Who thinks they can sing but really cannot?', '🎤'),
  ('q_cry_drunk', 'Who cries when they get drunk?', '🍺'),
  ('q_cancel', 'Who is most likely to cancel plans last minute?', '❌'),
  ('q_gym', 'Who posts too many gym selfies?', '💪'),
  ('q_eat', 'Who eats off everyone else''s plate?', '🍽️'),
  ('q_survive_woods', 'Who would die first in the wilderness?', '🏕️');
